"""Enum types for cmbenchmark."""

from enum import Enum
from typing import Literal


class WarningType(str, Enum):
    """Types of warnings that can occur during parsing."""
    UNKNOWN_NODE_TYPE = "UNKNOWN_NODE_TYPE"
    UNKNOWN_EDGE_TYPE = "UNKNOWN_EDGE_TYPE"
    DUPLICATE_ID = "DUPLICATE_ID"
    UNRESOLVED_REFERENCE = "UNRESOLVED_REFERENCE"
    INVALID_TYPE_REFERENCE = "INVALID_TYPE_REFERENCE"
    UNSUPPORTED_GENERIC_REFERENCE = "UNSUPPORTED_GENERIC_REFERENCE"
    MISSING_EDGE_ENDPOINT = "MISSING_EDGE_ENDPOINT"
    COMPATIBILITY_ADAPTATION = "COMPATIBILITY_ADAPTATION"
    MISSING_ATTRIBUTE = "MISSING_ATTRIBUTE"
    MULTIPLE_ROOT_PACKAGES = "MULTIPLE_ROOT_PACKAGES"
    UNHANDLED_ATTRIBUTE = "UNHANDLED_ATTRIBUTE"
    UNHANDLED_CHILD = "UNHANDLED_CHILD"
    DEFERRED_REF_UNRESOLVED = "DEFERRED_REF_UNRESOLVED"
    OTHER = "OTHER"


ParseStatus = Literal["success", "warning", "failure"]
